#!/usr/bin/env bash

# This script assembles a basic hello world yasm file
# and then runs it. The expected result is an "hello world" message.

# Abort on error
set -e

cd tests
yasm -felf test.asm 
gcc test.o -o test -m32
./test
