#!/usr/bin/env bash

# This script assembles a basic hello world yasm file
# and then runs it. The expected result is an "hello world" message.

# Abort on error
set -e

cd tests
mkdir -p build
yasm -felf test.asm -I../include
gcc test.o -o build/test -m32
./build/test
